apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
  namespace: {{ .Values.namespace }}
  labels:
    app: argushello
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: argushello
  template:
    metadata:
      labels:
        app: argushello
    spec:
      containers:
      - name: argushelloworld
        image: {{ .Values.image.repository }}
        ports:
        - containerPort: 5000
